package trueffect.truconnect.api.commons.model.importexport;

import trueffect.truconnect.api.commons.util.DateConverter;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import java.io.Serializable;
import java.text.ParseException;
import java.util.Date;

/**
 * Class that maps all Costs information for a given Package or Placement
 * Created by marcelo.heredia on 6/22/2016.
 * @author Marcelo Heredia
 */
public class CostDetailRawDataView extends RawDataView implements Serializable{
    private String plannedAdSpend;
    private String inventory;
    private String rate;
    private String rateType;
    private String startDate;
    private Date startDateDt;
    private String endDate;
    private Date endDateDt;
    private String rowNumber;

    //Internal fields
    private String plannedAdSpendAutoGenerated;
    private String rateAutoGenerated;
    private String rateTypeAutoGenerated;

    public CostDetailRawDataView() {
    }

    public CostDetailRawDataView(String plannedAdSpend, String inventory, String rate,
                                 String rateType, String startDate, String endDate) {
        super();
        this.plannedAdSpend = plannedAdSpend;
        this.inventory = inventory;
        this.rate = rate;
        this.rateType = rateType;
        this.setStartDate(startDate);
        this.setEndDate(endDate);
    }

    public String getPlannedAdSpend() {
        return plannedAdSpend;
    }

    public void setPlannedAdSpend(String plannedAdSpend) {
        this.plannedAdSpend = plannedAdSpend;
    }

    public String getInventory() {
        return inventory;
    }

    public void setInventory(String inventory) {
        this.inventory = inventory;
    }

    public String getRate() {
        return rate;
    }

    public void setRate(String rate) {
        this.rate = rate;
    }

    public String getRateType() {
        return rateType;
    }

    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        if(StringUtils.isBlank(startDate)) {
            this.startDate = startDate;
            this.startDateDt = null;
            return;
        }
        try {
            this.startDateDt = DateConverter.startDate(
                    DateConverter.parseXlsStringToDate(startDate));
            this.startDate = DateConverter.importExportFormat(this.startDateDt);
        } catch (ParseException e) {
            this.startDateDt = null;
            this.startDate = startDate;
        }
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        if(StringUtils.isBlank(endDate)) {
            this.endDate = endDate;
            this.endDateDt = null;
            return;
        }
        try {
            this.endDateDt = DateConverter.endDate(DateConverter.parseXlsStringToDate(endDate));
            this.endDate = DateConverter.importExportFormat(this.endDateDt);
        } catch (ParseException e) {
            this.endDateDt = null;
            this.endDate = endDate;
        }
    }

    public Date getStartDateDt() {
        return startDateDt;
    }

    public Date getEndDateDt() {
        return endDateDt;
    }

    public String getRowNumber() {
        return rowNumber;
    }

    public void setRowNumber(String rowNumber) {
        this.rowNumber = rowNumber;
    }

    public String getPlannedAdSpendAutoGenerated() {
        return plannedAdSpendAutoGenerated;
    }

    public void setPlannedAdSpendAutoGenerated(String plannedAdSpendAutoGenerated) {
        this.plannedAdSpendAutoGenerated = plannedAdSpendAutoGenerated;
    }

    public String getRateAutoGenerated() {
        return rateAutoGenerated;
    }

    public void setRateAutoGenerated(String rateAutoGenerated) {
        this.rateAutoGenerated = rateAutoGenerated;
    }

    public String getRateTypeAutoGenerated() {
        return rateTypeAutoGenerated;
    }

    public void setRateTypeAutoGenerated(String rateTypeAutoGenerated) {
        this.rateTypeAutoGenerated = rateTypeAutoGenerated;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
                .append(plannedAdSpend)
                .append(inventory)
                .append(rate)
                .append(rateType)
                .append(startDate)
                .append(endDate)
                .toHashCode();
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj instanceof CostDetailRawDataView) {
            final CostDetailRawDataView cost = (CostDetailRawDataView) obj;
            EqualsBuilder eb = new EqualsBuilder();

            if(StringUtils.isNotBlank(plannedAdSpend)) {
                eb.append(plannedAdSpend, cost.getPlannedAdSpend());
            }
            if(StringUtils.isNotBlank(inventory)) {
                eb.append(inventory, cost.getInventory());
            }
            if(StringUtils.isNotBlank(rate)) {
                eb.append(rate, cost.getRate());
            }
            if(StringUtils.isNotBlank(rateType)) {
                eb.append(rateType, cost.getRateType());
            }
            if(StringUtils.isNotBlank(startDate)) {
                eb.append(startDate, cost.getStartDate());
            }
            if(StringUtils.isNotBlank(endDate)) {
                eb.append(endDate, cost.getEndDate());
            }
            return eb.isEquals();
        } else {
            return false;
        }
    }
}
